import { sql } from 'drizzle-orm';
import {
  bigint,
  boolean,
  check,
  index,
  integer,
  jsonb,
  numeric,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  type AnyPgColumn,
} from 'drizzle-orm/pg-core';

const id = () => bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity();
const internalId = () => bigint('internal_id', { mode: 'number' }).notNull().generatedAlwaysAsIdentity();
const ts = (name: string) => timestamp(name, { withTimezone: true });
const createdAt = () => ts('created_at').notNull().defaultNow();
const updatedAt = () => ts('updated_at').notNull().defaultNow();
const metadata = (name: string) => jsonb(name).$type<Record<string, unknown>>().notNull().default(sql`'{}'::jsonb`);
const jsonArray = (name: string) => jsonb(name).$type<readonly Record<string, unknown>[]>().notNull().default(sql`'[]'::jsonb`);
const money = (name: string) => numeric(name, { precision: 20, scale: 8 });

export const authUser = pgTable(
  'auth_user',
  {
    internalId: internalId(),
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    email: text('email').notNull(),
    emailVerified: boolean('email_verified').notNull().default(false),
    image: text('image'),
    status: text('status').notNull().default('invited'),
    twoFactorEnabled: boolean('two_factor_enabled').notNull().default(false),
    productionEnabled: boolean('production_enabled').notNull().default(false),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    uniqueIndex('auth_user_internal_id_key').on(table.internalId),
    uniqueIndex('auth_user_email_key').on(table.email),
    check('auth_user_status_check', sql`${table.status} IN ('invited', 'active', 'disabled', 'deleted')`),
    check('auth_user_production_enabled_false', sql`${table.productionEnabled} = false`),
  ],
);

export const authSession = pgTable(
  'auth_session',
  {
    internalId: internalId(),
    id: text('id').primaryKey(),
    token: text('token').notNull(),
    expiresAt: ts('expires_at').notNull(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    userId: text('user_id').notNull().references(() => authUser.id, { onDelete: 'cascade' }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    uniqueIndex('auth_session_internal_id_key').on(table.internalId),
    uniqueIndex('auth_session_token_key').on(table.token),
    index('auth_session_user_id_idx').on(table.userId),
    index('auth_session_expires_at_idx').on(table.expiresAt),
  ],
);

export const authAccount = pgTable(
  'auth_account',
  {
    internalId: internalId(),
    id: text('id').primaryKey(),
    accountId: text('account_id').notNull(),
    userId: text('user_id').notNull().references(() => authUser.id, { onDelete: 'cascade' }),
    providerId: text('provider_id').notNull(),
    providerAccountId: text('provider_account_id'),
    password: text('password_hash'),
    accessToken: text('access_token_ciphertext'),
    accessTokenKeyId: text('access_token_key_id'),
    accessTokenAlgorithm: text('access_token_algorithm'),
    accessTokenNonce: text('access_token_nonce'),
    refreshToken: text('refresh_token_ciphertext'),
    refreshTokenKeyId: text('refresh_token_key_id'),
    refreshTokenAlgorithm: text('refresh_token_algorithm'),
    refreshTokenNonce: text('refresh_token_nonce'),
    accessTokenExpiresAt: ts('access_token_expires_at'),
    refreshTokenExpiresAt: ts('refresh_token_expires_at'),
    scope: text('scope'),
    idToken: text('id_token_ciphertext'),
    idTokenKeyId: text('id_token_key_id'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    uniqueIndex('auth_account_internal_id_key').on(table.internalId),
    uniqueIndex('auth_account_provider_account_id_key').on(table.providerId, table.accountId),
    uniqueIndex('auth_account_provider_account_key').on(table.providerId, table.providerAccountId),
    index('auth_account_user_id_idx').on(table.userId),
  ],
);

export const authVerification = pgTable(
  'auth_verification',
  {
    internalId: internalId(),
    id: text('id').primaryKey(),
    identifier: text('identifier').notNull(),
    value: text('value_hash').notNull(),
    expiresAt: ts('expires_at').notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    uniqueIndex('auth_verification_internal_id_key').on(table.internalId),
    index('auth_verification_identifier_idx').on(table.identifier),
    index('auth_verification_expires_at_idx').on(table.expiresAt),
  ],
);

export const authTwoFactor = pgTable(
  'auth_two_factor',
  {
    internalId: internalId(),
    id: text('id').primaryKey(),
    userId: text('user_id').notNull().references(() => authUser.id, { onDelete: 'cascade' }),
    secret: text('secret_ciphertext').notNull(),
    secretKeyId: text('secret_key_id'),
    secretAlgorithm: text('secret_algorithm'),
    secretNonce: text('secret_nonce'),
    backupCodes: text('backup_code_ciphertext'),
    backupCodeKeyId: text('backup_code_key_id'),
    backupCodeAlgorithm: text('backup_code_algorithm'),
    backupCodeNonce: text('backup_code_nonce'),
    status: text('status').notNull().default('pending'),
    verifiedAt: ts('verified_at'),
    disabledAt: ts('disabled_at'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    uniqueIndex('auth_two_factor_internal_id_key').on(table.internalId),
    index('auth_two_factor_user_id_idx').on(table.userId),
    check('auth_two_factor_status_check', sql`${table.status} IN ('pending', 'verified', 'disabled')`),
  ],
);

export const org = pgTable(
  'org',
  {
    id: id(),
    orgId: text('org_id').notNull(),
    name: text('name').notNull(),
    slug: text('slug').notNull(),
    status: text('status').notNull().default('draft'),
    productionEnabled: boolean('production_enabled').notNull().default(false),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    uniqueIndex('org_org_id_key').on(table.orgId),
    uniqueIndex('org_slug_key').on(table.slug),
    check('org_status_check', sql`${table.status} IN ('draft', 'active', 'disabled', 'archived')`),
    check('org_production_enabled_false', sql`${table.productionEnabled} = false`),
  ],
);

export const team = pgTable(
  'team',
  {
    id: id(),
    teamId: text('team_id').notNull(),
    orgId: bigint('org_id', { mode: 'number' }).notNull().references(() => org.id, { onDelete: 'restrict' }),
    name: text('name').notNull(),
    slug: text('slug').notNull(),
    status: text('status').notNull().default('draft'),
    productionEnabled: boolean('production_enabled').notNull().default(false),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    uniqueIndex('team_team_id_key').on(table.teamId),
    uniqueIndex('team_org_slug_key').on(table.orgId, table.slug),
    index('team_org_id_idx').on(table.orgId),
    check('team_status_check', sql`${table.status} IN ('draft', 'active', 'disabled', 'archived')`),
    check('team_production_enabled_false', sql`${table.productionEnabled} = false`),
  ],
);

export const project = pgTable(
  'project',
  {
    id: id(),
    projectId: text('project_id').notNull(),
    orgId: bigint('org_id', { mode: 'number' }).notNull().references(() => org.id, { onDelete: 'restrict' }),
    teamId: bigint('team_id', { mode: 'number' }).references(() => team.id, { onDelete: 'set null' }),
    name: text('name').notNull(),
    slug: text('slug').notNull(),
    environment: text('environment').notNull().default('development'),
    status: text('status').notNull().default('draft'),
    productionEnabled: boolean('production_enabled').notNull().default(false),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    uniqueIndex('project_project_id_key').on(table.projectId),
    uniqueIndex('project_org_slug_key').on(table.orgId, table.slug),
    index('project_org_id_idx').on(table.orgId),
    index('project_team_id_idx').on(table.teamId),
    check('project_environment_check', sql`${table.environment} IN ('development', 'staging', 'production', 'test')`),
    check('project_status_check', sql`${table.status} IN ('draft', 'active', 'disabled', 'archived')`),
    check('project_production_enabled_false', sql`${table.productionEnabled} = false`),
  ],
);

export const principal = pgTable(
  'principal',
  {
    id: id(),
    principalId: text('principal_id').notNull(),
    principalType: text('principal_type').notNull(),
    orgId: bigint('org_id', { mode: 'number' }).references(() => org.id, { onDelete: 'restrict' }),
    authUserId: text('auth_user_id').references(() => authUser.id, { onDelete: 'set null' }),
    displayName: text('display_name').notNull(),
    status: text('status').notNull().default('active'),
    productionEnabled: boolean('production_enabled').notNull().default(false),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    uniqueIndex('principal_principal_id_key').on(table.principalId),
    index('principal_org_id_idx').on(table.orgId),
    index('principal_auth_user_id_idx').on(table.authUserId),
    check('principal_type_check', sql`${table.principalType} IN ('user', 'service', 'system')`),
    check('principal_status_check', sql`${table.status} IN ('active', 'disabled', 'archived')`),
    check('principal_production_enabled_false', sql`${table.productionEnabled} = false`),
  ],
);

export const role = pgTable(
  'role',
  {
    id: id(),
    roleId: text('role_id').notNull(),
    orgId: bigint('org_id', { mode: 'number' }).references(() => org.id, { onDelete: 'restrict' }),
    name: text('name').notNull(),
    scopeType: text('scope_type').notNull(),
    status: text('status').notNull().default('active'),
    productionEnabled: boolean('production_enabled').notNull().default(false),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    uniqueIndex('role_role_id_key').on(table.roleId),
    uniqueIndex('role_org_name_key').on(table.orgId, table.name),
    index('role_org_id_idx').on(table.orgId),
    check('role_scope_type_check', sql`${table.scopeType} IN ('system', 'org', 'team', 'project')`),
    check('role_status_check', sql`${table.status} IN ('active', 'disabled', 'archived')`),
    check('role_production_enabled_false', sql`${table.productionEnabled} = false`),
  ],
);

export const permissionGrant = pgTable(
  'permission_grant',
  {
    id: id(),
    permissionGrantId: text('permission_grant_id').notNull(),
    principalId: bigint('principal_id', { mode: 'number' }).notNull().references(() => principal.id, { onDelete: 'restrict' }),
    roleId: bigint('role_id', { mode: 'number' }).notNull().references(() => role.id, { onDelete: 'restrict' }),
    orgId: bigint('org_id', { mode: 'number' }).references(() => org.id, { onDelete: 'restrict' }),
    teamId: bigint('team_id', { mode: 'number' }).references(() => team.id, { onDelete: 'restrict' }),
    projectId: bigint('project_id', { mode: 'number' }).references(() => project.id, { onDelete: 'restrict' }),
    resourceType: text('resource_type'),
    resourceRef: text('resource_ref'),
    permission: text('permission').notNull(),
    status: text('status').notNull().default('active'),
    effectiveFrom: ts('effective_from').notNull().defaultNow(),
    effectiveUntil: ts('effective_until'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    uniqueIndex('permission_grant_permission_grant_id_key').on(table.permissionGrantId),
    index('permission_grant_principal_id_idx').on(table.principalId),
    index('permission_grant_role_id_idx').on(table.roleId),
    index('permission_grant_org_id_idx').on(table.orgId),
    index('permission_grant_team_id_idx').on(table.teamId),
    index('permission_grant_project_id_idx').on(table.projectId),
    check('permission_grant_status_check', sql`${table.status} IN ('active', 'revoked', 'expired')`),
  ],
);

export const auditEvent = pgTable(
  'audit_event',
  {
    id: id(),
    auditEventId: text('audit_event_id').notNull(),
    eventName: text('event_name').notNull(),
    action: text('action').notNull(),
    outcome: text('outcome').notNull(),
    decision: text('decision'),
    reason: text('reason'),
    actorPrincipalId: bigint('actor_principal_id', { mode: 'number' }).references(() => principal.id, { onDelete: 'restrict' }),
    targetPrincipalId: bigint('target_principal_id', { mode: 'number' }).references(() => principal.id, { onDelete: 'restrict' }),
    projectId: bigint('project_id', { mode: 'number' }).references(() => project.id, { onDelete: 'restrict' }),
    virtualKeyId: bigint('virtual_key_id', { mode: 'number' }).references((): AnyPgColumn => virtualKey.id, { onDelete: 'restrict' }),
    budgetScopeId: bigint('budget_scope_id', { mode: 'number' }).references((): AnyPgColumn => budgetScope.id, { onDelete: 'restrict' }),
    authUserId: text('auth_user_id').references(() => authUser.id, { onDelete: 'restrict' }),
    traceId: text('trace_id').notNull(),
    requestId: text('request_id').notNull(),
    spanId: text('span_id'),
    policyVersion: text('policy_version'),
    registryVersion: text('registry_version'),
    environment: text('environment').notNull().default('development'),
    metadata: metadata('metadata'),
    createdAt: createdAt(),
  },
  (table) => [
    uniqueIndex('audit_event_audit_event_id_key').on(table.auditEventId),
    index('audit_event_actor_principal_id_idx').on(table.actorPrincipalId),
    index('audit_event_target_principal_id_idx').on(table.targetPrincipalId),
    index('audit_event_project_id_created_at_idx').on(table.projectId, table.createdAt),
    index('audit_event_virtual_key_id_idx').on(table.virtualKeyId),
    index('audit_event_budget_scope_id_idx').on(table.budgetScopeId),
    index('audit_event_auth_user_id_idx').on(table.authUserId),
    index('audit_event_trace_id_idx').on(table.traceId),
    index('audit_event_request_id_idx').on(table.requestId),
    index('audit_event_policy_registry_idx').on(table.policyVersion, table.registryVersion),
    check('audit_event_outcome_check', sql`${table.outcome} IN ('allow', 'deny', 'success', 'failure', 'error')`),
    check('audit_event_decision_check', sql`${table.decision} IS NULL OR ${table.decision} IN ('allow', 'deny')`),
    check('audit_event_environment_check', sql`${table.environment} IN ('development', 'staging', 'production', 'test')`),
  ],
);

export const budgetScope = pgTable(
  'budget_scope',
  {
    id: id(),
    budgetScopeId: text('budget_scope_id').notNull(),
    scopeType: text('scope_type').notNull(),
    ownerRef: text('owner_ref').notNull(),
    orgId: bigint('org_id', { mode: 'number' }).references(() => org.id, { onDelete: 'restrict' }),
    teamId: bigint('team_id', { mode: 'number' }).references(() => team.id, { onDelete: 'restrict' }),
    projectId: bigint('project_id', { mode: 'number' }).references(() => project.id, { onDelete: 'restrict' }),
    principalId: bigint('principal_id', { mode: 'number' }).references(() => principal.id, { onDelete: 'restrict' }),
    virtualKeyId: bigint('virtual_key_id', { mode: 'number' }).references((): AnyPgColumn => virtualKey.id, { onDelete: 'restrict' }),
    parentBudgetScopeId: bigint('parent_budget_scope_id', { mode: 'number' }).references((): AnyPgColumn => budgetScope.id, { onDelete: 'restrict' }),
    status: text('status').notNull().default('draft'),
    policyVersion: text('policy_version').notNull(),
    productionEnabled: boolean('production_enabled').notNull().default(false),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    uniqueIndex('budget_scope_budget_scope_id_key').on(table.budgetScopeId),
    index('budget_scope_scope_type_owner_ref_idx').on(table.scopeType, table.ownerRef),
    index('budget_scope_org_id_idx').on(table.orgId),
    index('budget_scope_team_id_idx').on(table.teamId),
    index('budget_scope_project_id_idx').on(table.projectId),
    index('budget_scope_principal_id_idx').on(table.principalId),
    index('budget_scope_virtual_key_id_idx').on(table.virtualKeyId),
    index('budget_scope_parent_budget_scope_id_idx').on(table.parentBudgetScopeId),
    check('budget_scope_scope_type_check', sql`${table.scopeType} IN ('org', 'team', 'project', 'principal', 'virtual_key')`),
    check('budget_scope_status_check', sql`${table.status} IN ('draft', 'active', 'disabled', 'archived')`),
    check('budget_scope_production_enabled_false', sql`${table.productionEnabled} = false`),
  ],
);

export const budgetPolicy = pgTable(
  'budget_policy',
  {
    id: id(),
    budgetPolicyId: text('budget_policy_id').notNull(),
    budgetScopeId: bigint('budget_scope_id', { mode: 'number' }).notNull().references(() => budgetScope.id, { onDelete: 'restrict' }),
    currency: text('currency').notNull(),
    hardCapAmount: money('hard_cap_amount'),
    softCapAmount: money('soft_cap_amount'),
    tokenCapInput: bigint('token_cap_input', { mode: 'number' }),
    tokenCapOutput: bigint('token_cap_output', { mode: 'number' }),
    tokenCapTotal: bigint('token_cap_total', { mode: 'number' }),
    resetPeriod: text('reset_period').notNull(),
    resetAnchor: ts('reset_anchor'),
    effectiveFrom: ts('effective_from').notNull().defaultNow(),
    effectiveUntil: ts('effective_until'),
    policyVersion: text('policy_version').notNull(),
    createdAuditEventId: bigint('created_audit_event_id', { mode: 'number' }).references(() => auditEvent.id, { onDelete: 'restrict' }),
    productionEnabled: boolean('production_enabled').notNull().default(false),
    createdAt: createdAt(),
  },
  (table) => [
    uniqueIndex('budget_policy_budget_policy_id_key').on(table.budgetPolicyId),
    index('budget_policy_budget_scope_effective_from_idx').on(table.budgetScopeId, table.effectiveFrom),
    index('budget_policy_created_audit_event_id_idx').on(table.createdAuditEventId),
    check('budget_policy_reset_period_check', sql`${table.resetPeriod} IN ('daily', 'weekly', 'monthly', 'rolling_24h', 'rolling_7d', 'rolling_30d', 'none')`),
    check('budget_policy_currency_check', sql`${table.currency} ~ '^[A-Z]{3}$'`),
    check('budget_policy_production_enabled_false', sql`${table.productionEnabled} = false`),
  ],
);

export const virtualKey = pgTable(
  'virtual_key',
  {
    id: id(),
    virtualKeyId: text('virtual_key_id').notNull(),
    keyPrefix: text('key_prefix').notNull(),
    keyFingerprint: text('key_fingerprint').notNull(),
    keyHash: text('key_hash').notNull(),
    principalId: bigint('principal_id', { mode: 'number' }).notNull().references(() => principal.id, { onDelete: 'restrict' }),
    principalType: text('principal_type').notNull(),
    projectId: bigint('project_id', { mode: 'number' }).notNull().references(() => project.id, { onDelete: 'restrict' }),
    budgetScopeId: bigint('budget_scope_id', { mode: 'number' }).notNull().references(() => budgetScope.id, { onDelete: 'restrict' }),
    environment: text('environment').notNull().default('development'),
    status: text('status').notNull().default('draft'),
    scopeConstraints: metadata('scope_constraints'),
    policyVersion: text('policy_version').notNull(),
    registryVersion: text('registry_version').notNull(),
    productionEnabled: boolean('production_enabled').notNull().default(false),
    issuedAt: ts('issued_at').notNull().defaultNow(),
    notBefore: ts('not_before'),
    expiresAt: ts('expires_at').notNull(),
    rotationOfKeyId: bigint('rotation_of_key_id', { mode: 'number' }).references((): AnyPgColumn => virtualKey.id, { onDelete: 'set null' }),
    rotatedToKeyId: bigint('rotated_to_key_id', { mode: 'number' }).references((): AnyPgColumn => virtualKey.id, { onDelete: 'set null' }),
    revokedAt: ts('revoked_at'),
    revokedByPrincipalId: bigint('revoked_by_principal_id', { mode: 'number' }).references(() => principal.id, { onDelete: 'restrict' }),
    revocationReason: text('revocation_reason'),
    lastUsedAt: ts('last_used_at'),
    lastUsedRequestId: text('last_used_request_id'),
    lastUsedTraceId: text('last_used_trace_id'),
    createdAuditEventId: bigint('created_audit_event_id', { mode: 'number' }).references(() => auditEvent.id, { onDelete: 'restrict' }),
    revokedAuditEventId: bigint('revoked_audit_event_id', { mode: 'number' }).references(() => auditEvent.id, { onDelete: 'restrict' }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    uniqueIndex('virtual_key_virtual_key_id_key').on(table.virtualKeyId),
    uniqueIndex('virtual_key_key_fingerprint_key').on(table.keyFingerprint),
    index('virtual_key_principal_project_status_idx').on(table.principalId, table.projectId, table.status),
    index('virtual_key_project_status_idx').on(table.projectId, table.status),
    index('virtual_key_budget_scope_id_idx').on(table.budgetScopeId),
    index('virtual_key_expires_at_idx').on(table.expiresAt),
    index('virtual_key_policy_version_idx').on(table.policyVersion),
    index('virtual_key_registry_version_idx').on(table.registryVersion),
    index('virtual_key_rotation_of_key_id_idx').on(table.rotationOfKeyId),
    index('virtual_key_rotated_to_key_id_idx').on(table.rotatedToKeyId),
    index('virtual_key_revoked_by_principal_id_idx').on(table.revokedByPrincipalId),
    index('virtual_key_created_audit_event_id_idx').on(table.createdAuditEventId),
    index('virtual_key_revoked_audit_event_id_idx').on(table.revokedAuditEventId),
    check('virtual_key_principal_type_check', sql`${table.principalType} IN ('user', 'service', 'system')`),
    check('virtual_key_environment_check', sql`${table.environment} IN ('development', 'staging', 'production', 'test')`),
    check('virtual_key_status_check', sql`${table.status} IN ('draft', 'active', 'rotating', 'revoked', 'expired', 'disabled')`),
    check('virtual_key_production_enabled_false', sql`${table.productionEnabled} = false`),
    check('virtual_key_revoked_requires_fields', sql`${table.status} <> 'revoked' OR (${table.revokedAt} IS NOT NULL AND ${table.revokedByPrincipalId} IS NOT NULL AND ${table.revocationReason} IS NOT NULL)`),
  ],
);

export const providerSnapshot = pgTable(
  'provider_snapshot',
  {
    id: id(),
    providerSnapshotId: text('provider_snapshot_id').notNull(),
    provider: text('provider').notNull(),
    registryVersion: text('registry_version').notNull(),
    policyVersion: text('policy_version').notNull(),
    environment: text('environment').notNull().default('development'),
    status: text('status').notNull().default('disabled'),
    productionEnabled: boolean('production_enabled').notNull().default(false),
    configChecksum: text('config_checksum').notNull(),
    providerConfig: metadata('provider_config'),
    providerKeyCiphertext: text('provider_key_ciphertext'),
    providerKeyId: text('provider_key_id'),
    providerKeyAlgorithm: text('provider_key_algorithm'),
    providerKeyNonce: text('provider_key_nonce'),
    providerKeyFingerprint: text('provider_key_fingerprint'),
    createdAuditEventId: bigint('created_audit_event_id', { mode: 'number' }).references(() => auditEvent.id, { onDelete: 'restrict' }),
    createdAt: createdAt(),
  },
  (table) => [
    uniqueIndex('provider_snapshot_provider_snapshot_id_key').on(table.providerSnapshotId),
    uniqueIndex('provider_snapshot_provider_registry_key').on(table.provider, table.registryVersion, table.environment),
    index('provider_snapshot_policy_version_idx').on(table.policyVersion),
    index('provider_snapshot_created_audit_event_id_idx').on(table.createdAuditEventId),
    check('provider_snapshot_status_check', sql`${table.status} IN ('draft', 'active', 'disabled', 'archived')`),
    check('provider_snapshot_environment_check', sql`${table.environment} IN ('development', 'staging', 'production', 'test')`),
    check('provider_snapshot_production_enabled_false', sql`${table.productionEnabled} = false`),
  ],
);

export const modelAliasSnapshot = pgTable(
  'model_alias_snapshot',
  {
    id: id(),
    modelAliasSnapshotId: text('model_alias_snapshot_id').notNull(),
    modelAlias: text('model_alias').notNull(),
    providerSnapshotId: bigint('provider_snapshot_id', { mode: 'number' }).references(() => providerSnapshot.id, { onDelete: 'restrict' }),
    provider: text('provider').notNull(),
    providerModelId: text('provider_model_id').notNull(),
    registryVersion: text('registry_version').notNull(),
    policyVersion: text('policy_version').notNull(),
    status: text('status').notNull().default('disabled'),
    productionEnabled: boolean('production_enabled').notNull().default(false),
    routingConfig: metadata('routing_config'),
    gateResultId: text('gate_result_id'),
    createdAuditEventId: bigint('created_audit_event_id', { mode: 'number' }).references(() => auditEvent.id, { onDelete: 'restrict' }),
    createdAt: createdAt(),
  },
  (table) => [
    uniqueIndex('model_alias_snapshot_model_alias_snapshot_id_key').on(table.modelAliasSnapshotId),
    uniqueIndex('model_alias_snapshot_alias_registry_key').on(table.modelAlias, table.registryVersion, table.provider),
    index('model_alias_snapshot_provider_snapshot_id_idx').on(table.providerSnapshotId),
    index('model_alias_snapshot_policy_version_idx').on(table.policyVersion),
    index('model_alias_snapshot_created_audit_event_id_idx').on(table.createdAuditEventId),
    check('model_alias_snapshot_status_check', sql`${table.status} IN ('draft', 'active', 'disabled', 'archived')`),
    check('model_alias_snapshot_production_enabled_false', sql`${table.productionEnabled} = false`),
  ],
);

export const policySnapshot = pgTable(
  'policy_snapshot',
  {
    id: id(),
    policySnapshotId: text('policy_snapshot_id').notNull(),
    policyVersion: text('policy_version').notNull(),
    status: text('status').notNull().default('draft'),
    productionEnabled: boolean('production_enabled').notNull().default(false),
    checksum: text('checksum').notNull(),
    policyPayload: metadata('policy_payload'),
    createdAuditEventId: bigint('created_audit_event_id', { mode: 'number' }).references(() => auditEvent.id, { onDelete: 'restrict' }),
    createdAt: createdAt(),
  },
  (table) => [
    uniqueIndex('policy_snapshot_policy_snapshot_id_key').on(table.policySnapshotId),
    uniqueIndex('policy_snapshot_policy_version_key').on(table.policyVersion),
    index('policy_snapshot_created_audit_event_id_idx').on(table.createdAuditEventId),
    check('policy_snapshot_status_check', sql`${table.status} IN ('draft', 'active', 'disabled', 'archived')`),
    check('policy_snapshot_production_enabled_false', sql`${table.productionEnabled} = false`),
  ],
);

export const costEvent = pgTable(
  'cost_event',
  {
    id: id(),
    costEventId: text('cost_event_id').notNull(),
    eventType: text('event_type').notNull(),
    requestId: text('request_id').notNull(),
    traceId: text('trace_id').notNull(),
    spanId: text('span_id'),
    principalId: bigint('principal_id', { mode: 'number' }).references(() => principal.id, { onDelete: 'restrict' }),
    projectId: bigint('project_id', { mode: 'number' }).notNull().references(() => project.id, { onDelete: 'restrict' }),
    virtualKeyId: bigint('virtual_key_id', { mode: 'number' }).references(() => virtualKey.id, { onDelete: 'restrict' }),
    budgetScopeId: bigint('budget_scope_id', { mode: 'number' }).notNull().references(() => budgetScope.id, { onDelete: 'restrict' }),
    policyVersion: text('policy_version').notNull(),
    registryVersion: text('registry_version').notNull(),
    environment: text('environment').notNull().default('development'),
    routeIntent: text('route_intent').notNull(),
    dataClass: text('data_class').notNull(),
    provider: text('provider'),
    modelAlias: text('model_alias').notNull(),
    providerModelId: text('provider_model_id'),
    gatewayAttempt: integer('gateway_attempt').notNull().default(1),
    fallbackAttempt: integer('fallback_attempt').notNull().default(0),
    attemptStatus: text('attempt_status').notNull(),
    currency: text('currency').notNull(),
    estimatedInputTokens: bigint('estimated_input_tokens', { mode: 'number' }),
    estimatedOutputTokens: bigint('estimated_output_tokens', { mode: 'number' }),
    estimatedTotalTokens: bigint('estimated_total_tokens', { mode: 'number' }),
    estimatedCostAmount: money('estimated_cost_amount'),
    actualInputTokens: bigint('actual_input_tokens', { mode: 'number' }),
    actualOutputTokens: bigint('actual_output_tokens', { mode: 'number' }),
    actualTotalTokens: bigint('actual_total_tokens', { mode: 'number' }),
    actualCostAmount: money('actual_cost_amount'),
    usageSource: text('usage_source').notNull(),
    decision: text('decision').notNull(),
    denialReason: text('denial_reason'),
    budgetReservationLedgerId: bigint('budget_reservation_ledger_id', { mode: 'number' }).references((): AnyPgColumn => budgetLedger.id, { onDelete: 'restrict' }),
    auditEventId: bigint('audit_event_id', { mode: 'number' }).references(() => auditEvent.id, { onDelete: 'restrict' }),
    metadata: metadata('metadata'),
    createdAt: createdAt(),
  },
  (table) => [
    uniqueIndex('cost_event_cost_event_id_key').on(table.costEventId),
    index('cost_event_budget_scope_created_at_idx').on(table.budgetScopeId, table.createdAt),
    index('cost_event_project_created_at_idx').on(table.projectId, table.createdAt),
    index('cost_event_virtual_key_created_at_idx').on(table.virtualKeyId, table.createdAt),
    index('cost_event_provider_model_created_at_idx').on(table.provider, table.modelAlias, table.createdAt),
    index('cost_event_request_id_idx').on(table.requestId),
    index('cost_event_trace_id_idx').on(table.traceId),
    index('cost_event_policy_registry_idx').on(table.policyVersion, table.registryVersion),
    index('cost_event_environment_route_data_idx').on(table.environment, table.routeIntent, table.dataClass),
    index('cost_event_principal_id_idx').on(table.principalId),
    index('cost_event_budget_reservation_ledger_id_idx').on(table.budgetReservationLedgerId),
    index('cost_event_audit_event_id_idx').on(table.auditEventId),
    check('cost_event_event_type_check', sql`${table.eventType} IN ('estimate', 'actual', 'reconciliation', 'denial_estimate')`),
    check('cost_event_attempt_status_check', sql`${table.attemptStatus} IN ('started', 'succeeded', 'failed', 'denied', 'cancelled', 'timed_out')`),
    check('cost_event_usage_source_check', sql`${table.usageSource} IN ('registry_estimate', 'gateway_counter', 'provider_reported', 'estimated_final', 'not_available')`),
    check('cost_event_decision_check', sql`${table.decision} IN ('allow', 'deny')`),
    check('cost_event_denial_reason_check', sql`${table.decision} <> 'deny' OR ${table.denialReason} IS NOT NULL`),
  ],
);

export const budgetLedger = pgTable(
  'budget_ledger',
  {
    id: id(),
    ledgerEntryId: text('ledger_entry_id').notNull(),
    budgetScopeId: bigint('budget_scope_id', { mode: 'number' }).notNull().references(() => budgetScope.id, { onDelete: 'restrict' }),
    requestId: text('request_id').notNull(),
    traceId: text('trace_id').notNull(),
    costEventId: bigint('cost_event_id', { mode: 'number' }).references(() => costEvent.id, { onDelete: 'restrict' }),
    entryType: text('entry_type').notNull(),
    amount: money('amount'),
    currency: text('currency').notNull(),
    inputTokens: bigint('input_tokens', { mode: 'number' }),
    outputTokens: bigint('output_tokens', { mode: 'number' }),
    totalTokens: bigint('total_tokens', { mode: 'number' }),
    status: text('status').notNull().default('pending'),
    resetPeriodStart: ts('reset_period_start').notNull(),
    resetPeriodEnd: ts('reset_period_end').notNull(),
    createdAt: createdAt(),
  },
  (table) => [
    uniqueIndex('budget_ledger_ledger_entry_id_key').on(table.ledgerEntryId),
    index('budget_ledger_budget_scope_window_idx').on(table.budgetScopeId, table.resetPeriodStart, table.resetPeriodEnd),
    index('budget_ledger_request_id_idx').on(table.requestId),
    index('budget_ledger_trace_id_idx').on(table.traceId),
    index('budget_ledger_cost_event_id_idx').on(table.costEventId),
    check('budget_ledger_entry_type_check', sql`${table.entryType} IN ('reservation', 'reservation_release', 'actual', 'adjustment')`),
    check('budget_ledger_status_check', sql`${table.status} IN ('pending', 'committed', 'released', 'voided')`),
  ],
);

export const requestLog = pgTable(
  'request_log',
  {
    id: id(),
    requestLogId: text('request_log_id').notNull(),
    requestId: text('request_id').notNull(),
    traceId: text('trace_id').notNull(),
    spanId: text('span_id'),
    parentSpanId: text('parent_span_id'),
    principalId: bigint('principal_id', { mode: 'number' }).references(() => principal.id, { onDelete: 'restrict' }),
    projectId: bigint('project_id', { mode: 'number' }).references(() => project.id, { onDelete: 'restrict' }),
    virtualKeyId: bigint('virtual_key_id', { mode: 'number' }).references(() => virtualKey.id, { onDelete: 'restrict' }),
    budgetScopeId: bigint('budget_scope_id', { mode: 'number' }).references(() => budgetScope.id, { onDelete: 'restrict' }),
    costEventId: bigint('cost_event_id', { mode: 'number' }).references(() => costEvent.id, { onDelete: 'restrict' }),
    auditEventId: bigint('audit_event_id', { mode: 'number' }).references(() => auditEvent.id, { onDelete: 'restrict' }),
    environment: text('environment').notNull().default('development'),
    routeIntent: text('route_intent').notNull(),
    dataClass: text('data_class').notNull(),
    provider: text('provider'),
    modelAlias: text('model_alias'),
    providerModelId: text('provider_model_id'),
    gatewayAttempt: integer('gateway_attempt').notNull().default(1),
    fallbackAttempt: integer('fallback_attempt').notNull().default(0),
    decision: text('decision').notNull(),
    denialReason: text('denial_reason'),
    statusCode: integer('status_code'),
    latencyMs: integer('latency_ms'),
    policyVersion: text('policy_version').notNull(),
    registryVersion: text('registry_version').notNull(),
    metadata: metadata('metadata'),
    createdAt: createdAt(),
  },
  (table) => [
    uniqueIndex('request_log_request_log_id_key').on(table.requestLogId),
    index('request_log_request_id_idx').on(table.requestId),
    index('request_log_trace_id_idx').on(table.traceId),
    index('request_log_principal_created_at_idx').on(table.principalId, table.createdAt),
    index('request_log_project_created_at_idx').on(table.projectId, table.createdAt),
    index('request_log_virtual_key_created_at_idx').on(table.virtualKeyId, table.createdAt),
    index('request_log_budget_scope_created_at_idx').on(table.budgetScopeId, table.createdAt),
    index('request_log_cost_event_id_idx').on(table.costEventId),
    index('request_log_audit_event_id_idx').on(table.auditEventId),
    index('request_log_policy_registry_idx').on(table.policyVersion, table.registryVersion),
    check('request_log_decision_check', sql`${table.decision} IN ('allow', 'deny')`),
    check('request_log_environment_check', sql`${table.environment} IN ('development', 'staging', 'production', 'test')`),
  ],
);

export const breakGlassActivation = pgTable(
  'break_glass_activation',
  {
    id: id(),
    breakGlassActivationId: text('break_glass_activation_id').notNull(),
    projectId: bigint('project_id', { mode: 'number' }).notNull().references(() => project.id, { onDelete: 'restrict' }),
    requestedByPrincipalId: bigint('requested_by_principal_id', { mode: 'number' }).notNull().references(() => principal.id, { onDelete: 'restrict' }),
    approvedByPrincipalId: bigint('approved_by_principal_id', { mode: 'number' }).references(() => principal.id, { onDelete: 'restrict' }),
    activatedByPrincipalId: bigint('activated_by_principal_id', { mode: 'number' }).references(() => principal.id, { onDelete: 'restrict' }),
    status: text('status').notNull().default('requested'),
    environment: text('environment').notNull().default('development'),
    productionEnabled: boolean('production_enabled').notNull().default(false),
    reason: text('reason').notNull(),
    policyVersion: text('policy_version').notNull(),
    registryVersion: text('registry_version'),
    tokenCiphertext: text('token_ciphertext'),
    tokenKeyId: text('token_key_id'),
    tokenAlgorithm: text('token_algorithm'),
    tokenNonce: text('token_nonce'),
    tokenFingerprint: text('token_fingerprint'),
    startsAt: ts('starts_at'),
    expiresAt: ts('expires_at').notNull(),
    activatedAt: ts('activated_at'),
    revokedAt: ts('revoked_at'),
    createdAuditEventId: bigint('created_audit_event_id', { mode: 'number' }).references(() => auditEvent.id, { onDelete: 'restrict' }),
    activatedAuditEventId: bigint('activated_audit_event_id', { mode: 'number' }).references(() => auditEvent.id, { onDelete: 'restrict' }),
    revokedAuditEventId: bigint('revoked_audit_event_id', { mode: 'number' }).references(() => auditEvent.id, { onDelete: 'restrict' }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    uniqueIndex('break_glass_activation_id_key').on(table.breakGlassActivationId),
    index('break_glass_activation_project_id_idx').on(table.projectId),
    index('break_glass_activation_requested_by_idx').on(table.requestedByPrincipalId),
    index('break_glass_activation_approved_by_idx').on(table.approvedByPrincipalId),
    index('break_glass_activation_activated_by_idx').on(table.activatedByPrincipalId),
    index('break_glass_activation_created_audit_event_id_idx').on(table.createdAuditEventId),
    index('break_glass_activation_activated_audit_event_id_idx').on(table.activatedAuditEventId),
    index('break_glass_activation_revoked_audit_event_id_idx').on(table.revokedAuditEventId),
    check('break_glass_activation_status_check', sql`${table.status} IN ('requested', 'approved', 'activated', 'denied', 'revoked', 'expired')`),
    check('break_glass_activation_environment_check', sql`${table.environment} IN ('development', 'staging', 'production', 'test')`),
    check('break_glass_activation_production_enabled_false', sql`${table.productionEnabled} = false`),
  ],
);

export const evalGateResult = pgTable(
  'eval_gate_result',
  {
    id: id(),
    gateResultId: text('gate_result_id').notNull(),
    changeId: text('change_id').notNull(),
    datasetVersion: text('dataset_version').notNull(),
    evalSuiteVersion: text('eval_suite_version').notNull(),
    runnerVersion: text('runner_version').notNull(),
    targetKind: text('target_kind').notNull(),
    artifactVersion: text('artifact_version').notNull(),
    modelAlias: text('model_alias'),
    provider: text('provider'),
    retrievalStrategyId: text('retrieval_strategy_id'),
    promptTemplateId: text('prompt_template_id'),
    toolName: text('tool_name'),
    skillId: text('skill_id'),
    indexId: text('index_id'),
    metrics: metadata('metrics'),
    thresholds: metadata('thresholds'),
    pass: boolean('pass').notNull(),
    blockingSeverity: text('blocking_severity').notNull(),
    ownerApprovalRequired: boolean('owner_approval_required').notNull().default(false),
    reviewerPrincipalId: bigint('reviewer_principal_id', { mode: 'number' }).references(() => principal.id, { onDelete: 'restrict' }),
    reviewedAt: ts('reviewed_at'),
    approverPrincipalId: bigint('approver_principal_id', { mode: 'number' }).references(() => principal.id, { onDelete: 'restrict' }),
    approvedAt: ts('approved_at'),
    approvalReason: text('approval_reason'),
    artifactRefs: jsonArray('artifact_refs'),
    artifactStoragePolicyRef: text('artifact_storage_policy_ref').notNull(),
    retentionPolicyRef: text('retention_policy_ref').notNull(),
    auditEventId: bigint('audit_event_id', { mode: 'number' }).notNull().references(() => auditEvent.id, { onDelete: 'restrict' }),
    traceId: text('trace_id'),
    requestId: text('request_id'),
    createdAt: createdAt(),
  },
  (table) => [
    uniqueIndex('eval_gate_result_gate_result_id_key').on(table.gateResultId),
    index('eval_gate_result_match_key_idx').on(table.changeId, table.datasetVersion, table.evalSuiteVersion, table.artifactVersion),
    index('eval_gate_result_audit_event_id_idx').on(table.auditEventId),
    index('eval_gate_result_reviewer_principal_id_idx').on(table.reviewerPrincipalId),
    index('eval_gate_result_approver_principal_id_idx').on(table.approverPrincipalId),
    index('eval_gate_result_trace_id_idx').on(table.traceId),
    index('eval_gate_result_request_id_idx').on(table.requestId),
    check('eval_gate_result_target_kind_check', sql`${table.targetKind} IN ('model_alias', 'fallback_route', 'tool', 'prompt_template', 'retrieval_strategy', 'skill', 'index_version')`),
    check('eval_gate_result_blocking_severity_check', sql`${table.blockingSeverity} IN ('none', 'low', 'medium', 'high', 'critical')`),
    check('eval_gate_result_pass_requires_no_blocking_severity', sql`${table.pass} = false OR ${table.blockingSeverity} = 'none'`),
    check('eval_gate_result_owner_approval_requires_approver', sql`${table.ownerApprovalRequired} = false OR ${table.approverPrincipalId} IS NOT NULL`),
  ],
);
