export const nonProductionFixtureSeed = {
  id: 'non-production-fixtures',
  purpose: 'Fixture metadata for development, local smoke tests, and disposable environments only.',
  productionAllowed: false,
  autoRunAtBoot: false,
  storesPlaintextCredentials: false,
  storesProviderKeys: false,
  fixtureClasses: [
    'demo_org',
    'demo_project',
    'disabled_provider_candidate',
    'policy_snapshot_stub',
    'track2_supervisor_subagent_definitions',
    'track2_workflow',
    'track2_delegation',
    'track2_readonly_tool_policy',
    'track2_skill_definition_version',
    'track2_idempotency_lease_smoke',
    'track2_artifact_metadata',
  ],
  fixtureCatalog: [
    {
      className: 'demo_org',
      track: 'foundation',
      purpose: 'Describe a disposable organization fixture root.',
      expectedTableFamilies: ['org', 'team', 'principal', 'role', 'permission_grant', 'audit_event'],
    },
    {
      className: 'demo_project',
      track: 'foundation',
      purpose: 'Describe a disposable project fixture under the demo organization.',
      expectedTableFamilies: ['project', 'principal', 'budget_scope', 'budget_policy', 'audit_event'],
    },
    {
      className: 'disabled_provider_candidate',
      track: 'foundation',
      purpose: 'Describe disabled provider/model registry rows with refs only.',
      expectedTableFamilies: ['provider_snapshot', 'model_alias_snapshot', 'audit_event'],
    },
    {
      className: 'policy_snapshot_stub',
      track: 'foundation',
      purpose: 'Describe a non-production policy snapshot stub.',
      expectedTableFamilies: ['policy_snapshot', 'audit_event'],
    },
    {
      className: 'track2_supervisor_subagent_definitions',
      track: 'track2',
      purpose: 'Discover supervisor and sub-agent definition fixture metadata.',
      expectedTableFamilies: ['agent_definition', 'principal', 'project', 'budget_scope', 'audit_event'],
      expectedKinds: ['supervisor', 'planner', 'researcher', 'synthesizer', 'reviewer', 'tool_executor'],
    },
    {
      className: 'track2_workflow',
      track: 'track2',
      purpose: 'Discover a workflow fixture shell with run, step, and event metadata.',
      expectedTableFamilies: ['workflow_run', 'workflow_step', 'workflow_event', 'agent_run', 'budget_scope', 'audit_event'],
      expectedStates: ['created', 'planning', 'delegating', 'running', 'waiting_on_child', 'synthesizing', 'completed'],
    },
    {
      className: 'track2_delegation',
      track: 'track2',
      purpose: 'Discover delegation fixture metadata for supervisor-to-sub-agent handoff.',
      expectedTableFamilies: ['delegation', 'delegation_result', 'agent_run', 'workflow_event', 'budget_scope', 'audit_event'],
      expectedStates: ['queued', 'dispatched', 'running', 'succeeded'],
    },
    {
      className: 'track2_readonly_tool_policy',
      track: 'track2',
      purpose: 'Discover read-only tool definition and policy fixture metadata.',
      expectedTableFamilies: ['tool_definition', 'tool_policy', 'tool_call', 'budget_scope', 'audit_event'],
      expectedAccessModes: ['read_only'],
      expectedPolicyEffects: ['allow', 'review', 'deny'],
    },
    {
      className: 'track2_skill_definition_version',
      track: 'track2',
      purpose: 'Discover skill definition and version fixture metadata.',
      expectedTableFamilies: ['skill_definition', 'skill_version', 'eval_gate_result', 'budget_scope', 'audit_event'],
      expectedSkillClasses: ['workflow', 'tool', 'analysis', 'retrieval', 'synthesis', 'guardrail'],
    },
    {
      className: 'track2_idempotency_lease_smoke',
      track: 'track2',
      purpose: 'Discover idempotency and lease smoke fixture metadata.',
      expectedTableFamilies: ['workflow_idempotency_key', 'workflow_lease', 'workflow_event', 'audit_event'],
      expectedOperations: ['workflow_create', 'step_execute', 'delegation_create', 'agent_run', 'tool_call', 'artifact_write', 'skill_register', 'skill_version_register'],
    },
    {
      className: 'track2_artifact_metadata',
      track: 'track2',
      purpose: 'Discover artifact metadata fixture refs without artifact contents.',
      expectedTableFamilies: ['task_artifact', 'workflow_event', 'eval_gate_result', 'audit_event'],
      expectedArtifactKinds: ['plan', 'delegation_result', 'tool_output', 'review_note', 'package_ref'],
    },
  ],
  safetyBoundary: {
    environmentScope: 'non-production',
    dataShape: 'refs-and-descriptive-metadata-only',
    containsRawPayloads: false,
    containsCredentialMaterial: false,
    containsProviderKeyMaterial: false,
  },
} as const;

export type NonProductionFixtureSeed = typeof nonProductionFixtureSeed;
